refactor(pie-modal): DSW-000 pie modal page object refactor
justeattakeaway/pie pull request #1359
Opened 2024-03-26 16:39 UTC by JoshuaNg2332

## Describe your changes (can list changeset entries if preferable)
- Updated pie modal page object to match format in pie cookie banner

## Author Checklist (complete before requesting a review)
- [ ] I have performed a self-review of my code

## Reviewer checklists (complete before approving)
### Reviewer 1
- [ ] If it is a `PIE Docs` change, I have reviewed the PR preview

### Reviewer 2
- [ ] If it is a `PIE Docs` change, I have reviewed the PR preview

2024-03-26 16:53 UTC, jamieomaguire submitted a review, later dismissed

2024-03-27 10:24 UTC, siggerzz commented on packages/components/pie-modal/test/component/pie-modal.spec.ts
> +let modalPage: PieModalComponent;
Probably worth updating these to `modalComponent`

2024-03-27 10:25 UTC, siggerzz requested changes
Minor comment regarding variables name!

2024-03-27 10:44 UTC, jamieomaguire submitted a review, later dismissed

2024-03-27 11:05 UTC, siggerzz commented on packages/components/pie-modal/test/component/pie-modal.spec.ts
> +        const modal = await modalComponent.isModalVisible();
Could you we change this to `isModalVisible`?

2024-03-27 11:06 UTC, siggerzz commented on packages/components/pie-modal/test/component/pie-modal.spec.ts
> +        const modal = await modalComponent.isModalVisible();
Or change to `expect(await modalComponent.isModalVisible()).toBe(true);` so it's consistent with other tests.

2024-03-27 11:08 UTC, siggerzz requested changes
Few minor comments around naming

2024-03-27 12:56 UTC, siggerzz approved these changes

2024-03-27 15:56 UTC, xander-marjoram approved these changes
Lovely stuff

2024-03-27 16:01 UTC, merged