Spacing token descriptions (global and alias)
justeattakeaway/pie pull request #161
Opened 2023-02-06 22:27 UTC by raoufswe

- adds Spacing token descriptions (global and alias)

2023-02-07 08:48 UTC, jamieomaguire commented on apps/pie-microsite/src/assets/styles/components/_tokensTable.scss
> +
@raoufswe could we chat about this? Not quite sure why this has been added as the previous styles for the global token used were signed off by jordi. Looking on the PR preview, the margin seems to be incorrect on this PR

<img width="540" alt="Screenshot 2023-02-07 at 08 47 55" src="https://user-images.githubusercontent.com/16766185/217196169-41d09764-e39f-4176-a758-b1252addfbd6.png">
<img width="670" alt="Screenshot 2023-02-07 at 08 47 46" src="https://user-images.githubusercontent.com/16766185/217196172-bb5c8751-0efa-41b0-980f-a2cdeeabbfad.png">

2023-02-07 08:49 UTC, jamieomaguire requested changes
Just setting to request changes so we can catch up about the global tokens stuff :)

2023-02-07 11:25 UTC, FayeCarter submitted a review, later dismissed

2023-02-07 11:33 UTC, fernandofranca approved these changes

2023-02-07 11:38 UTC, jamieomaguire requested changes
we've updated the spacing in figma - can explain in a message or on a call but good to align with the other tokens

2023-02-08 17:03 UTC, LTurns approved these changes

2023-02-09 08:25 UTC, fernandofranca approved these changes

2023-02-09 09:33 UTC, jamieomaguire approved these changes

2023-02-09 09:33 UTC, jamieomaguire commented
LGTM - awesome work @raoufswe 🎉

2023-02-09 09:40 UTC, merged