test(pie-link): DSW-2229 updated visual tests to split by size
justeattakeaway/pie pull request #1952
Opened 2024-09-25 15:52 UTC by JoshuaNg2332

## Describe your changes (can list changeset entries if preferable)
- Updated Pie Link tests to split the variations up by size.
- Screenshots should increase from **3** to **6** in number

This is to resolve issues such as:
- Screenshotted variations being cropped due to too large of a screenshot
- Improve screenshot readability and reviewability. 

## Author Checklist (complete before requesting a review)
- [ ] I have performed a self-review of my code
- [ ] I have reviewed visual test updates properly before approving
- [ ] If changes will affect consumers of the package, I have created a changeset entry.

## Reviewer checklists (complete before approving)
### Reviewer 1
- [ ] I have reviewed the `PIE Storybook`/`PIE Docs` PR preview
- [ ] If there are visual test updates, I have reviewed them

### Reviewer 2
- [ ] I have reviewed the `PIE Storybook`/`PIE Docs` PR preview
- [ ] If there are visual test updates, I have reviewed them

2024-09-27 11:55 UTC, maledr5 submitted a review, later dismissed
Change looks good. I checked in Percy and shows missing images that I assume are the old ones, but confused on why it shows as missing instead of removed. Is this a known issue to us?

2024-09-27 12:52 UTC, xander-marjoram commented
@maledr5 Yep "missing" is just the terminology used. As long as we're happy that only the removed screenshots are missing then that's all good.

2024-09-27 13:20 UTC, siggerzz commented on .changeset/afraid-shoes-cough.md
> +Updated visual tests to split by size
Probably wouldn't create a changeset for this as it result in a package bump that doesnt affect consumers.

2024-09-27 13:20 UTC, siggerzz requested changes
Minor comment

2024-09-30 09:37 UTC, siggerzz approved these changes

2024-09-30 11:58 UTC, kevinrodrigues approved these changes

2024-10-01 09:57 UTC, merged