chore(pie-monorepo): DSW-000 update several package versions to resolve security warnings
justeattakeaway/pie pull request #1953
Opened 2024-09-26 09:54 UTC by xander-marjoram

## Describe your changes (can list changeset entries if preferable)
- Combines the following automated PRs:
- #1948 
- #1942 
- #1687 

## Author Checklist (complete before requesting a review)
- [ ] I have performed a self-review of my code
- [ ] I have reviewed the `PIE Storybook`/`PIE Docs` PR preview
- [x] If changes will affect consumers of the package, I have created a changeset entry.
- [ ] If a changeset file has been created, I have used the `/snapit` functionality to test my changes in a consuming application

## Reviewer checklists (complete before approving)
### Reviewer 1
- [ ] I have reviewed the `PIE Storybook`/`PIE Docs` PR preview
- [ ] If there are visual test updates, I have reviewed them

### Reviewer 2
- [ ] I have reviewed the `PIE Storybook`/`PIE Docs` PR preview
- [ ] If there are visual test updates, I have reviewed them

2024-09-27 09:41 UTC, xander-marjoram commented
/test-aperture

2024-09-27 13:23 UTC, siggerzz requested changes
Small comment regarding changeset file!

2024-09-30 12:11 UTC, siggerzz approved these changes

2024-09-30 12:15 UTC, kevinrodrigues approved these changes

2024-09-30 12:16 UTC, raoufswe approved these changes

2024-09-30 12:17 UTC, merged