docs(pie-docs) - Use simpleTable on global spacing tokens page
justeattakeaway/pie pull request #558
Opened 2023-06-21 10:27 UTC by xander-marjoram

## Describe your changes (can list changeset entries if preferable)

## Author Checklist (complete before requesting a review)
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] If it is a `PIE Docs` change, I have reviewed the Docs site preview
- [ ] If it is a component change, I have reviewed the Storybook preview
- [ ] If there are visual test updates, I have reviewed them properly before approving

## Reviewer checklists (complete before approving)
### Reviewer 1
- [ ] If it is a `PIE Docs` change, I have reviewed the PR preview
- [ ] If there are visual test updates, I have reviewed them

### Reviewer 2
- [ ] If it is a `PIE Docs` change, I have reviewed the PR preview
- [ ] If there are visual test updates, I have reviewed them

2023-06-21 13:41 UTC, jordifornellsJET commented
@xander-marjoram just checked this, here are a couple of questions:

- The text appears to be 16px, not 14px for the table elements. It looks quite oversized when compared.
- Not necessarily tied to this ticket, but just noticed now: The notification component uses $content-subdued instead of $content-default. Who should I raise this with?

Everything else looks fine, thanks!

2023-06-21 13:43 UTC, jordifornellsJET requested changes
Just checked this, here are a couple of questions:

- The text appears to be 16px, not 14px for the table elements. It looks quite oversized when compared.
- Not necessarily tied to this ticket, but just noticed now: The notification component uses $content-subdued instead of $content-default. Who should I raise this with?

Everything else looks fine, thanks!

2023-06-21 14:07 UTC, kevinrodrigues submitted a review, later dismissed

2023-06-21 16:05 UTC, xander-marjoram commented
I've updated the font size for monospaced tables to 14px. The notification font colour is a strange one so let's address that one in another ticket.

2023-06-22 08:21 UTC, kevinrodrigues approved these changes

2023-06-22 14:28 UTC, merged